### PR TITLE
Fix for issue #23: SF OOB backup doesn't show proper backup type

### PR DESCRIPTION
**Pull request by sauravmndl**
For details please look into following reference
https://github.com/SAP/service-fabrik-broker/issues/23

### CODE REVIEW

**Comment by muralisc** [comment]
HI rebase against master.
Some of my changes have creeped up in your pull as new changes.  See: https://github.com/SAP/service-fabrik-broker/pull/27/commits/19d48caab58d21ce7fe3d39d87eca9ec8dc22499

**Comment by sauravmndl** [comment]
@muralisc  Done. Please check, once the review is done and further changes applied (if any) I'll create a single commit.

**Comment by muralisc** [comment]
Nitpick: Better commit description? 
See https://wiki.openstack.org/wiki/GitCommitMessages
under section:
Do not assume the reviewer has access to external web services/site

**Comment by muralisc** [comment]
Oops my bad, mixed commit description with PR. 
Two LGTM.
So Merging.

**Pull request merged**
